languageCode = "en-us"
title = "Azure Blog"
# Enable comments by entering your Disqus shortname
disqusShortname = "fredderfblog"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-90173119-1"
# Define the number of posts per page
paginate = 7
footnotereturnlinkcontents = "↩"
theme = "hugotheme"
#uglyurls = true
enableemoji = true

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "Michael Friedrich"
    bio = "Cloud Solution Architect"
    location = "Sydney, Australia"
    site_description = "Michael Friedrich Azure Blog"
    copyright  = "Powered by [Hugo](//gohugo.io) and [Azure Blob Storage](https://azure.microsoft.com/en-au/services/storage/blobs/)"
    avatar = "img/me128.png"
    logo = "img/logo.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

    disable_mathjax = true

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "About Me"
    #link   = "page/aboutme.html"
    link = "page/aboutme/"

[[params.menu]]
    before = false
    label  = "Tags"
    #link   = "tags.html"
    link = "tags/"

[[params.menu]]
    before = false
    label  = "Posts"
    #link   = "post.html"
    link = "post/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/fredderf204"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "fredderf204"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "1michaelfriedrich"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "fredderf204"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = false
    tags = true
    tag_cloud = false

[blackfriday]
    hrefTargetBlank = true